name: PackageCI
on:
  push:
    branches:
      - master
      - releases/*
env:
  unity_exe: 'C:\Program Files\Unity\Hub\Editor\2019.3.3f1\Editor\Unity.exe'

jobs:
  checkout:
    runs-on: [self-hosted, windows, x64]
    steps:        
     - name: checkout
       uses: actions/checkout@v2.0.0
       with:
         lfs: true  
         clean: false      
  uploadGoogleDrive:
    runs-on: [self-hosted, windows, x64]
    steps:
      - name: Upload to Google Drive
        uses: satackey/action-google-drive@v1.1.0
        with:
          # Content of `~/.skicka.tokencache.json` created by the `skicka` command
          skicka-tokencache-json: test
          # The path where the files to upload are located
          upload-from: ./game/ # optional, default is ./
          # The path where the files to be uploaded is located
          upload-to: https://drive.google.com/drive/u/3/my-drive
          # Whether to delete files that do not exist locally
          # remove-outdated: # optional, default is true
          # Your Google Drive API client ID
          # google-client-id: # optional
          # Your Google Drive API client secret
          # google-client-secret: # optional

